CREATE DATABASE IF NOT EXISTS arca_soa_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE arca_soa_db;

CREATE TABLE IF NOT EXISTS t_validacion_cliente (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_cliente VARCHAR(50) NOT NULL,
  habilitado TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_sincronizacion_erp_wms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_pedido VARCHAR(50) NOT NULL,
  estado_wms VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_generacion_guia (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_pedido VARCHAR(50) NOT NULL,
  numero_guia VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_cierre_pedido_erp (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_pedido VARCHAR(50) NOT NULL,
  estado_erp VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_auditoria (
  id INT AUTO_INCREMENT PRIMARY KEY,
  operacion VARCHAR(100) NOT NULL,
  id_pedido VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
